CREATE DATABASE JSANCHEZECOMMERS
USE JSANCHEZECOMMERS
GO

CREATE TABLE DESCUENTO
(
IDDESCUENTO INT IDENTITY(1,1) PRIMARY KEY,
VALOR DECIMAL(3,2) NOT NULL
)
GO

CREATE TABLE CATEGORIA
(
IDCATEGORIA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
)
GO

CREATE TABLE PRODUCTO
(
IDPRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(50) NOT NULL,
PRECIO DECIMAL NOT NULL,
PRECIOVENTA DECIMAL NOT NULL,
CODIGOBARRA VARCHAR(MAX) NOT NULL,
STOCK INT NOT NULL,
IMAGEN VARCHAR(MAX) NOT NULL,
IDCATEGORIA INT NOT NULL,
IDDESCUENTO INT NOT NULL,
CONSTRAINT FK_CategoriaProducto FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA (IDCATEGORIA),
CONSTRAINT FK_DescuentoProducto FOREIGN KEY (IDDESCUENTO) REFERENCES DESCUENTO(IDDESCUENTO)
)
GO

-----------------------------PRODUCTO-------------------------
CREATE PROCEDURE ProductoAdd --'Dell 4512','AX-4342FD',2000,'KJDSFKSDBKSDB',3,10
@NOMBRE VARCHAR(50),
@DESCRIPCION VARCHAR(50),
@PRECIO DECIMAL,
@PRECIOVENTA DECIMAL,
@CODIGOBARRA VARCHAR(MAX),
@STOCK INT,
@IMAGEN VARCHAR(MAX),
@IDCATEGORIA INT,
@IDDESCUENTO INT
AS
INSERT INTO PRODUCTO(NOMBRE,DESCRIPCION,PRECIO,PRECIOVENTA,CODIGOBARRA,STOCK,IMAGEN,IDCATEGORIA,IDDESCUENTO)
VALUES (@NOMBRE,@DESCRIPCION,@PRECIO,@PRECIOVENTA,@CODIGOBARRA,@STOCK,@IMAGEN,@IDCATEGORIA,@IDDESCUENTO)
GO

CREATE PROCEDURE ProductoUpdate
@IDPRODUCTO INT,
@NOMBRE VARCHAR(50),
@DESCRIPCION VARCHAR(50),
@PRECIO DECIMAL,
@PRECIOVENTA DECIMAL,
@CODIGOBARRA VARCHAR(MAX),
@STOCK INT,
@IMAGEN VARCHAR(MAX),
@IDCATEGORIA INT,
@IDDESCUENTO INT
AS
UPDATE PRODUCTO SET NOMBRE=@NOMBRE,DESCRIPCION=@DESCRIPCION,PRECIO=@PRECIO,PRECIOVENTA=@PRECIOVENTA,
CODIGOBARRA=@CODIGOBARRA,STOCK=@STOCK,IMAGEN=@IMAGEN,IDCATEGORIA=@IDCATEGORIA,IDDESCUENTO=@IDDESCUENTO
WHERE IDPRODUCTO=@IDPRODUCTO
GO

CREATE PROCEDURE ProductoDelete
@IDPRODUCTO INT
AS
DELETE FROM PRODUCTO WHERE IDPRODUCTO=@IDPRODUCTO
GO

CREATE PROCEDURE ProductoGetAll --'',0
@NOMBRE VARCHAR(50),
@IDCATEGORIA INT
AS
BEGIN
DECLARE @sql NVARCHAR(MAX);
SET @sql = 
'SELECT P.IDPRODUCTO,P.NOMBRE,P.DESCRIPCION,P.PRECIO,P.PRECIOVENTA,P.CODIGOBARRA,
P.STOCK,P.IMAGEN,C.IDCATEGORIA,C.NOMBRE AS NombreCategoria,D.IDDESCUENTO,D.VALOR FROM PRODUCTO P
INNER JOIN CATEGORIA C ON P.IDCATEGORIA = C.IDCATEGORIA
INNER JOIN DESCUENTO D ON P.IDDESCUENTO = D.IDDESCUENTO';
IF @NOMBRE IS NOT NULL AND LEN(@NOMBRE) > 0
        SET @sql = @sql + ' WHERE UPPER(P.NOMBRE) LIKE UPPER(''%' + @NOMBRE + '%'')';
        
    IF @IDCATEGORIA IS NOT NULL AND @IDCATEGORIA <> 0
        SET @sql = @sql + ' AND C.IDCATEGORIA = @IDCATEGORIA';
EXEC sp_executesql @sql,
N'@NOMBRE VARCHAR(50), @IDCATEGORIA INT',
@NOMBRE, @IDCATEGORIA;
END;
GO

CREATE PROCEDURE ProductoGetById
@IDPRODUCTO INT
AS
SELECT P.IDPRODUCTO,P.NOMBRE,P.DESCRIPCION,P.PRECIO,P.PRECIOVENTA,P.CODIGOBARRA,
P.STOCK,P.IMAGEN,C.IDCATEGORIA,C.NOMBRE AS NombreCategoria,D.IDDESCUENTO,D.VALOR FROM PRODUCTO P
INNER JOIN CATEGORIA C ON P.IDCATEGORIA = C.IDCATEGORIA
INNER JOIN DESCUENTO D ON P.IDDESCUENTO = D.IDDESCUENTO
WHERE IDPRODUCTO = @IDPRODUCTO
GO
-------------------CATEGORIA--------------------
CREATE PROCEDURE CategoriaAdd
@NOMBRE VARCHAR(50)
AS
INSERT INTO CATEGORIA(NOMBRE) VALUES(@NOMBRE)
GO

CREATE PROCEDURE CategoriaUpdate
@IDCATEGORIA INT,
@NOMBRE VARCHAR(50)
AS
UPDATE CATEGORIA SET NOMBRE=@NOMBRE WHERE IDCATEGORIA=@IDCATEGORIA
GO

CREATE PROCEDURE CategoriaDelete
@IDCATEGORIA INT
AS
DELETE FROM CATEGORIA WHERE IDCATEGORIA=@IDCATEGORIA
GO

CREATE PROCEDURE CategoriaGetAll
AS
SELECT IDCATEGORIA,NOMBRE FROM CATEGORIA
GO

CREATE PROCEDURE CategoriaGetById
@IDCATEGORIA INT
AS
SELECT IDCATEGORIA,NOMBRE FROM CATEGORIA WHERE IDCATEGORIA=@IDCATEGORIA
GO

CREATE PROCEDURE DescuentoAdd
@VALOR DECIMAL(3,2)
AS
INSERT INTO DESCUENTO (VALOR) VALUES (@VALOR)
GO

CREATE PROCEDURE DescuentoGetAll
AS
SELECT IDDESCUENTO,VALOR FROM DESCUENTO
GO

CREATE PROCEDURE DescuentoGetById
@IDDESCUENTO INT
AS
SELECT IDDESCUENTO,VALOR FROM DESCUENTO WHERE IDDESCUENTO=@IDDESCUENTO
GO

DescuentoAdd 0
GO
DescuentoAdd 0.25
GO
DescuentoAdd 0.50
GO
DescuentoAdd 0.75
GO